// Generated by scripts/import-topic-plan.mjs.
import type { ComponentType } from "react";
import TailwindV4CssFirstZh, { metadata as TailwindV4CssFirstZhMetadata } from "@/content/posts/tailwind-v4-css-first/zh-TW.mdx";
import TailwindV4CssFirstEn, { metadata as TailwindV4CssFirstEnMetadata } from "@/content/posts/tailwind-v4-css-first/en.mdx";
import CraAfterlifeZh, { metadata as CraAfterlifeZhMetadata } from "@/content/posts/cra-afterlife/zh-TW.mdx";
import CraAfterlifeEn, { metadata as CraAfterlifeEnMetadata } from "@/content/posts/cra-afterlife/en.mdx";
import BybitSafeUiZh, { metadata as BybitSafeUiZhMetadata } from "@/content/posts/bybit-safe-ui/zh-TW.mdx";
import BybitSafeUiEn, { metadata as BybitSafeUiEnMetadata } from "@/content/posts/bybit-safe-ui/en.mdx";
import TypescriptNativePortZh, { metadata as TypescriptNativePortZhMetadata } from "@/content/posts/typescript-native-port/zh-TW.mdx";
import TypescriptNativePortEn, { metadata as TypescriptNativePortEnMetadata } from "@/content/posts/typescript-native-port/en.mdx";
import CustomSelectZh, { metadata as CustomSelectZhMetadata } from "@/content/posts/custom-select/zh-TW.mdx";
import CustomSelectEn, { metadata as CustomSelectEnMetadata } from "@/content/posts/custom-select/en.mdx";
import Angular20Zh, { metadata as Angular20ZhMetadata } from "@/content/posts/angular-20/zh-TW.mdx";
import Angular20En, { metadata as Angular20EnMetadata } from "@/content/posts/angular-20/en.mdx";
import ChromeIo2025Zh, { metadata as ChromeIo2025ZhMetadata } from "@/content/posts/chrome-io-2025/zh-TW.mdx";
import ChromeIo2025En, { metadata as ChromeIo2025EnMetadata } from "@/content/posts/chrome-io-2025/en.mdx";
import Node24Zh, { metadata as Node24ZhMetadata } from "@/content/posts/node-24/zh-TW.mdx";
import Node24En, { metadata as Node24EnMetadata } from "@/content/posts/node-24/en.mdx";
import Vite7BaselineZh, { metadata as Vite7BaselineZhMetadata } from "@/content/posts/vite-7-baseline/zh-TW.mdx";
import Vite7BaselineEn, { metadata as Vite7BaselineEnMetadata } from "@/content/posts/vite-7-baseline/en.mdx";
import Safari26WebPlatformZh, { metadata as Safari26WebPlatformZhMetadata } from "@/content/posts/safari-26-web-platform/zh-TW.mdx";
import Safari26WebPlatformEn, { metadata as Safari26WebPlatformEnMetadata } from "@/content/posts/safari-26-web-platform/en.mdx";
import Nuxt4Zh, { metadata as Nuxt4ZhMetadata } from "@/content/posts/nuxt-4/zh-TW.mdx";
import Nuxt4En, { metadata as Nuxt4EnMetadata } from "@/content/posts/nuxt-4/en.mdx";
import TailwindPlusVanillaJsZh, { metadata as TailwindPlusVanillaJsZhMetadata } from "@/content/posts/tailwind-plus-vanilla-js/zh-TW.mdx";
import TailwindPlusVanillaJsEn, { metadata as TailwindPlusVanillaJsEnMetadata } from "@/content/posts/tailwind-plus-vanilla-js/en.mdx";
import NxS1ngularityZh, { metadata as NxS1ngularityZhMetadata } from "@/content/posts/nx-s1ngularity/zh-TW.mdx";
import NxS1ngularityEn, { metadata as NxS1ngularityEnMetadata } from "@/content/posts/nx-s1ngularity/en.mdx";
import NuxtUiV4Zh, { metadata as NuxtUiV4ZhMetadata } from "@/content/posts/nuxt-ui-v4/zh-TW.mdx";
import NuxtUiV4En, { metadata as NuxtUiV4EnMetadata } from "@/content/posts/nuxt-ui-v4/en.mdx";
import ReactFoundationZh, { metadata as ReactFoundationZhMetadata } from "@/content/posts/react-foundation/zh-TW.mdx";
import ReactFoundationEn, { metadata as ReactFoundationEnMetadata } from "@/content/posts/react-foundation/en.mdx";
import Angular21Zh, { metadata as Angular21ZhMetadata } from "@/content/posts/angular-21/zh-TW.mdx";
import Angular21En, { metadata as Angular21EnMetadata } from "@/content/posts/angular-21/en.mdx";
import NpmClassicTokenZh, { metadata as NpmClassicTokenZhMetadata } from "@/content/posts/npm-classic-token/zh-TW.mdx";
import NpmClassicTokenEn, { metadata as NpmClassicTokenEnMetadata } from "@/content/posts/npm-classic-token/en.mdx";
import React2shellZh, { metadata as React2shellZhMetadata } from "@/content/posts/react2shell/zh-TW.mdx";
import React2shellEn, { metadata as React2shellEnMetadata } from "@/content/posts/react2shell/en.mdx";
import Astro6BetaZh, { metadata as Astro6BetaZhMetadata } from "@/content/posts/astro-6-beta/zh-TW.mdx";
import Astro6BetaEn, { metadata as Astro6BetaEnMetadata } from "@/content/posts/astro-6-beta/en.mdx";
import MattPocockSkillsZh, { metadata as MattPocockSkillsZhMetadata } from "@/content/posts/matt-pocock-skills/zh-TW.mdx";
import MattPocockSkillsEn, { metadata as MattPocockSkillsEnMetadata } from "@/content/posts/matt-pocock-skills/en.mdx";
import Vite8RolldownZh, { metadata as Vite8RolldownZhMetadata } from "@/content/posts/vite-8-rolldown/zh-TW.mdx";
import Vite8RolldownEn, { metadata as Vite8RolldownEnMetadata } from "@/content/posts/vite-8-rolldown/en.mdx";
import Typescript6Zh, { metadata as Typescript6ZhMetadata } from "@/content/posts/typescript-6/zh-TW.mdx";
import Typescript6En, { metadata as Typescript6EnMetadata } from "@/content/posts/typescript-6/en.mdx";
import Chrome147Zh, { metadata as Chrome147ZhMetadata } from "@/content/posts/chrome-147/zh-TW.mdx";
import Chrome147En, { metadata as Chrome147EnMetadata } from "@/content/posts/chrome-147/en.mdx";
import WebmcpZh, { metadata as WebmcpZhMetadata } from "@/content/posts/webmcp/zh-TW.mdx";
import WebmcpEn, { metadata as WebmcpEnMetadata } from "@/content/posts/webmcp/en.mdx";
import Astro7Zh, { metadata as Astro7ZhMetadata } from "@/content/posts/astro-7/zh-TW.mdx";
import Astro7En, { metadata as Astro7EnMetadata } from "@/content/posts/astro-7/en.mdx";
import Typescript7Zh, { metadata as Typescript7ZhMetadata } from "@/content/posts/typescript-7/zh-TW.mdx";
import Typescript7En, { metadata as Typescript7EnMetadata } from "@/content/posts/typescript-7/en.mdx";
import Nuxt45Zh, { metadata as Nuxt45ZhMetadata } from "@/content/posts/nuxt-4-5/zh-TW.mdx";
import Nuxt45En, { metadata as Nuxt45EnMetadata } from "@/content/posts/nuxt-4-5/en.mdx";
import ColdcardRngZh, { metadata as ColdcardRngZhMetadata } from "@/content/posts/coldcard-rng/zh-TW.mdx";
import ColdcardRngEn, { metadata as ColdcardRngEnMetadata } from "@/content/posts/coldcard-rng/en.mdx";
import ChaindropNpmZh, { metadata as ChaindropNpmZhMetadata } from "@/content/posts/chaindrop-npm/zh-TW.mdx";
import ChaindropNpmEn, { metadata as ChaindropNpmEnMetadata } from "@/content/posts/chaindrop-npm/en.mdx";
import { Locale } from "@/types/i18n";
import type { Post, PostMetadata } from "@/types/post";

function createPost(locale: Locale, Body: ComponentType, metadata: PostMetadata): Post {
  return { ...metadata, locale, Body };
}

export const topicPosts: Post[] = [
  createPost(Locale.ZH_TW, TailwindV4CssFirstZh, TailwindV4CssFirstZhMetadata),
  createPost(Locale.EN, TailwindV4CssFirstEn, TailwindV4CssFirstEnMetadata),
  createPost(Locale.ZH_TW, CraAfterlifeZh, CraAfterlifeZhMetadata),
  createPost(Locale.EN, CraAfterlifeEn, CraAfterlifeEnMetadata),
  createPost(Locale.ZH_TW, BybitSafeUiZh, BybitSafeUiZhMetadata),
  createPost(Locale.EN, BybitSafeUiEn, BybitSafeUiEnMetadata),
  createPost(Locale.ZH_TW, TypescriptNativePortZh, TypescriptNativePortZhMetadata),
  createPost(Locale.EN, TypescriptNativePortEn, TypescriptNativePortEnMetadata),
  createPost(Locale.ZH_TW, CustomSelectZh, CustomSelectZhMetadata),
  createPost(Locale.EN, CustomSelectEn, CustomSelectEnMetadata),
  createPost(Locale.ZH_TW, Angular20Zh, Angular20ZhMetadata),
  createPost(Locale.EN, Angular20En, Angular20EnMetadata),
  createPost(Locale.ZH_TW, ChromeIo2025Zh, ChromeIo2025ZhMetadata),
  createPost(Locale.EN, ChromeIo2025En, ChromeIo2025EnMetadata),
  createPost(Locale.ZH_TW, Node24Zh, Node24ZhMetadata),
  createPost(Locale.EN, Node24En, Node24EnMetadata),
  createPost(Locale.ZH_TW, Vite7BaselineZh, Vite7BaselineZhMetadata),
  createPost(Locale.EN, Vite7BaselineEn, Vite7BaselineEnMetadata),
  createPost(Locale.ZH_TW, Safari26WebPlatformZh, Safari26WebPlatformZhMetadata),
  createPost(Locale.EN, Safari26WebPlatformEn, Safari26WebPlatformEnMetadata),
  createPost(Locale.ZH_TW, Nuxt4Zh, Nuxt4ZhMetadata),
  createPost(Locale.EN, Nuxt4En, Nuxt4EnMetadata),
  createPost(Locale.ZH_TW, TailwindPlusVanillaJsZh, TailwindPlusVanillaJsZhMetadata),
  createPost(Locale.EN, TailwindPlusVanillaJsEn, TailwindPlusVanillaJsEnMetadata),
  createPost(Locale.ZH_TW, NxS1ngularityZh, NxS1ngularityZhMetadata),
  createPost(Locale.EN, NxS1ngularityEn, NxS1ngularityEnMetadata),
  createPost(Locale.ZH_TW, NuxtUiV4Zh, NuxtUiV4ZhMetadata),
  createPost(Locale.EN, NuxtUiV4En, NuxtUiV4EnMetadata),
  createPost(Locale.ZH_TW, ReactFoundationZh, ReactFoundationZhMetadata),
  createPost(Locale.EN, ReactFoundationEn, ReactFoundationEnMetadata),
  createPost(Locale.ZH_TW, Angular21Zh, Angular21ZhMetadata),
  createPost(Locale.EN, Angular21En, Angular21EnMetadata),
  createPost(Locale.ZH_TW, NpmClassicTokenZh, NpmClassicTokenZhMetadata),
  createPost(Locale.EN, NpmClassicTokenEn, NpmClassicTokenEnMetadata),
  createPost(Locale.ZH_TW, React2shellZh, React2shellZhMetadata),
  createPost(Locale.EN, React2shellEn, React2shellEnMetadata),
  createPost(Locale.ZH_TW, Astro6BetaZh, Astro6BetaZhMetadata),
  createPost(Locale.EN, Astro6BetaEn, Astro6BetaEnMetadata),
  createPost(Locale.ZH_TW, MattPocockSkillsZh, MattPocockSkillsZhMetadata),
  createPost(Locale.EN, MattPocockSkillsEn, MattPocockSkillsEnMetadata),
  createPost(Locale.ZH_TW, Vite8RolldownZh, Vite8RolldownZhMetadata),
  createPost(Locale.EN, Vite8RolldownEn, Vite8RolldownEnMetadata),
  createPost(Locale.ZH_TW, Typescript6Zh, Typescript6ZhMetadata),
  createPost(Locale.EN, Typescript6En, Typescript6EnMetadata),
  createPost(Locale.ZH_TW, Chrome147Zh, Chrome147ZhMetadata),
  createPost(Locale.EN, Chrome147En, Chrome147EnMetadata),
  createPost(Locale.ZH_TW, WebmcpZh, WebmcpZhMetadata),
  createPost(Locale.EN, WebmcpEn, WebmcpEnMetadata),
  createPost(Locale.ZH_TW, Astro7Zh, Astro7ZhMetadata),
  createPost(Locale.EN, Astro7En, Astro7EnMetadata),
  createPost(Locale.ZH_TW, Typescript7Zh, Typescript7ZhMetadata),
  createPost(Locale.EN, Typescript7En, Typescript7EnMetadata),
  createPost(Locale.ZH_TW, Nuxt45Zh, Nuxt45ZhMetadata),
  createPost(Locale.EN, Nuxt45En, Nuxt45EnMetadata),
  createPost(Locale.ZH_TW, ColdcardRngZh, ColdcardRngZhMetadata),
  createPost(Locale.EN, ColdcardRngEn, ColdcardRngEnMetadata),
  createPost(Locale.ZH_TW, ChaindropNpmZh, ChaindropNpmZhMetadata),
  createPost(Locale.EN, ChaindropNpmEn, ChaindropNpmEnMetadata),
];
