// Generated by scripts/import-topic-plan.mjs.
import type { ComponentType } from "react";
import TailwindV4CssFirst, { metadata as TailwindV4CssFirstMetadata } from "@/content/posts/tailwind-v4-css-first/zh-TW.mdx";
import CraAfterlife, { metadata as CraAfterlifeMetadata } from "@/content/posts/cra-afterlife/zh-TW.mdx";
import BybitSafeUi, { metadata as BybitSafeUiMetadata } from "@/content/posts/bybit-safe-ui/zh-TW.mdx";
import TypescriptNativePort, { metadata as TypescriptNativePortMetadata } from "@/content/posts/typescript-native-port/zh-TW.mdx";
import CustomSelect, { metadata as CustomSelectMetadata } from "@/content/posts/custom-select/zh-TW.mdx";
import Angular20, { metadata as Angular20Metadata } from "@/content/posts/angular-20/zh-TW.mdx";
import ChromeIo2025, { metadata as ChromeIo2025Metadata } from "@/content/posts/chrome-io-2025/zh-TW.mdx";
import Node24, { metadata as Node24Metadata } from "@/content/posts/node-24/zh-TW.mdx";
import Vite7Baseline, { metadata as Vite7BaselineMetadata } from "@/content/posts/vite-7-baseline/zh-TW.mdx";
import Safari26WebPlatform, { metadata as Safari26WebPlatformMetadata } from "@/content/posts/safari-26-web-platform/zh-TW.mdx";
import Nuxt4, { metadata as Nuxt4Metadata } from "@/content/posts/nuxt-4/zh-TW.mdx";
import TailwindPlusVanillaJs, { metadata as TailwindPlusVanillaJsMetadata } from "@/content/posts/tailwind-plus-vanilla-js/zh-TW.mdx";
import NxS1ngularity, { metadata as NxS1ngularityMetadata } from "@/content/posts/nx-s1ngularity/zh-TW.mdx";
import NuxtUiV4, { metadata as NuxtUiV4Metadata } from "@/content/posts/nuxt-ui-v4/zh-TW.mdx";
import ReactFoundation, { metadata as ReactFoundationMetadata } from "@/content/posts/react-foundation/zh-TW.mdx";
import Angular21, { metadata as Angular21Metadata } from "@/content/posts/angular-21/zh-TW.mdx";
import NpmClassicToken, { metadata as NpmClassicTokenMetadata } from "@/content/posts/npm-classic-token/zh-TW.mdx";
import React2shell, { metadata as React2shellMetadata } from "@/content/posts/react2shell/zh-TW.mdx";
import Astro6Beta, { metadata as Astro6BetaMetadata } from "@/content/posts/astro-6-beta/zh-TW.mdx";
import MattPocockSkills, { metadata as MattPocockSkillsMetadata } from "@/content/posts/matt-pocock-skills/zh-TW.mdx";
import Vite8Rolldown, { metadata as Vite8RolldownMetadata } from "@/content/posts/vite-8-rolldown/zh-TW.mdx";
import Typescript6, { metadata as Typescript6Metadata } from "@/content/posts/typescript-6/zh-TW.mdx";
import Chrome147, { metadata as Chrome147Metadata } from "@/content/posts/chrome-147/zh-TW.mdx";
import Webmcp, { metadata as WebmcpMetadata } from "@/content/posts/webmcp/zh-TW.mdx";
import Astro7, { metadata as Astro7Metadata } from "@/content/posts/astro-7/zh-TW.mdx";
import Angular22, { metadata as Angular22Metadata } from "@/content/posts/angular-22/zh-TW.mdx";
import Typescript7, { metadata as Typescript7Metadata } from "@/content/posts/typescript-7/zh-TW.mdx";
import Nuxt45, { metadata as Nuxt45Metadata } from "@/content/posts/nuxt-4-5/zh-TW.mdx";
import ColdcardRng, { metadata as ColdcardRngMetadata } from "@/content/posts/coldcard-rng/zh-TW.mdx";
import AgentPlugins1, { metadata as AgentPlugins1Metadata } from "@/content/posts/agent-plugins-1/zh-TW.mdx";
import { Locale } from "@/types/i18n";
import type { Post, PostMetadata } from "@/types/post";

function createPost(Body: ComponentType, metadata: PostMetadata): Post {
  return { ...metadata, locale: Locale.ZH_TW, Body };
}

export const topicPosts: Post[] = [
  createPost(TailwindV4CssFirst, TailwindV4CssFirstMetadata),
  createPost(CraAfterlife, CraAfterlifeMetadata),
  createPost(BybitSafeUi, BybitSafeUiMetadata),
  createPost(TypescriptNativePort, TypescriptNativePortMetadata),
  createPost(CustomSelect, CustomSelectMetadata),
  createPost(Angular20, Angular20Metadata),
  createPost(ChromeIo2025, ChromeIo2025Metadata),
  createPost(Node24, Node24Metadata),
  createPost(Vite7Baseline, Vite7BaselineMetadata),
  createPost(Safari26WebPlatform, Safari26WebPlatformMetadata),
  createPost(Nuxt4, Nuxt4Metadata),
  createPost(TailwindPlusVanillaJs, TailwindPlusVanillaJsMetadata),
  createPost(NxS1ngularity, NxS1ngularityMetadata),
  createPost(NuxtUiV4, NuxtUiV4Metadata),
  createPost(ReactFoundation, ReactFoundationMetadata),
  createPost(Angular21, Angular21Metadata),
  createPost(NpmClassicToken, NpmClassicTokenMetadata),
  createPost(React2shell, React2shellMetadata),
  createPost(Astro6Beta, Astro6BetaMetadata),
  createPost(MattPocockSkills, MattPocockSkillsMetadata),
  createPost(Vite8Rolldown, Vite8RolldownMetadata),
  createPost(Typescript6, Typescript6Metadata),
  createPost(Chrome147, Chrome147Metadata),
  createPost(Webmcp, WebmcpMetadata),
  createPost(Astro7, Astro7Metadata),
  createPost(Angular22, Angular22Metadata),
  createPost(Typescript7, Typescript7Metadata),
  createPost(Nuxt45, Nuxt45Metadata),
  createPost(ColdcardRng, ColdcardRngMetadata),
  createPost(AgentPlugins1, AgentPlugins1Metadata),
];
