// Generated by scripts/import-topic-plan.mjs.
import type { ComponentType } from "react";
import TailwindV4CssFirstZh, { metadata as TailwindV4CssFirstZhMetadata } from "@/content/posts/tailwind-v4-css-first/zh-TW.mdx";
import TailwindV4CssFirstEn, { metadata as TailwindV4CssFirstEnMetadata } from "@/content/posts/tailwind-v4-css-first/en.mdx";
import LetsencryptExpirationEmailsZh, { metadata as LetsencryptExpirationEmailsZhMetadata } from "@/content/posts/letsencrypt-expiration-emails/zh-TW.mdx";
import LetsencryptExpirationEmailsEn, { metadata as LetsencryptExpirationEmailsEnMetadata } from "@/content/posts/letsencrypt-expiration-emails/en.mdx";
import BybitSafeUiZh, { metadata as BybitSafeUiZhMetadata } from "@/content/posts/bybit-safe-ui/zh-TW.mdx";
import BybitSafeUiEn, { metadata as BybitSafeUiEnMetadata } from "@/content/posts/bybit-safe-ui/en.mdx";
import GithubSecretRiskAssessmentZh, { metadata as GithubSecretRiskAssessmentZhMetadata } from "@/content/posts/github-secret-risk-assessment/zh-TW.mdx";
import GithubSecretRiskAssessmentEn, { metadata as GithubSecretRiskAssessmentEnMetadata } from "@/content/posts/github-secret-risk-assessment/en.mdx";
import CustomSelectZh, { metadata as CustomSelectZhMetadata } from "@/content/posts/custom-select/zh-TW.mdx";
import CustomSelectEn, { metadata as CustomSelectEnMetadata } from "@/content/posts/custom-select/en.mdx";
import ChromeIo2025Zh, { metadata as ChromeIo2025ZhMetadata } from "@/content/posts/chrome-io-2025/zh-TW.mdx";
import ChromeIo2025En, { metadata as ChromeIo2025EnMetadata } from "@/content/posts/chrome-io-2025/en.mdx";
import FigmaSitesZh, { metadata as FigmaSitesZhMetadata } from "@/content/posts/figma-sites/zh-TW.mdx";
import FigmaSitesEn, { metadata as FigmaSitesEnMetadata } from "@/content/posts/figma-sites/en.mdx";
import Vite7BaselineZh, { metadata as Vite7BaselineZhMetadata } from "@/content/posts/vite-7-baseline/zh-TW.mdx";
import Vite7BaselineEn, { metadata as Vite7BaselineEnMetadata } from "@/content/posts/vite-7-baseline/en.mdx";
import Safari26WebPlatformZh, { metadata as Safari26WebPlatformZhMetadata } from "@/content/posts/safari-26-web-platform/zh-TW.mdx";
import Safari26WebPlatformEn, { metadata as Safari26WebPlatformEnMetadata } from "@/content/posts/safari-26-web-platform/en.mdx";
import TailwindPlusVanillaJsZh, { metadata as TailwindPlusVanillaJsZhMetadata } from "@/content/posts/tailwind-plus-vanilla-js/zh-TW.mdx";
import TailwindPlusVanillaJsEn, { metadata as TailwindPlusVanillaJsEnMetadata } from "@/content/posts/tailwind-plus-vanilla-js/en.mdx";
import CloudflareAiCrawlControlZh, { metadata as CloudflareAiCrawlControlZhMetadata } from "@/content/posts/cloudflare-ai-crawl-control/zh-TW.mdx";
import CloudflareAiCrawlControlEn, { metadata as CloudflareAiCrawlControlEnMetadata } from "@/content/posts/cloudflare-ai-crawl-control/en.mdx";
import NuxtUiV4Zh, { metadata as NuxtUiV4ZhMetadata } from "@/content/posts/nuxt-ui-v4/zh-TW.mdx";
import NuxtUiV4En, { metadata as NuxtUiV4EnMetadata } from "@/content/posts/nuxt-ui-v4/en.mdx";
import Bun13HtmlZh, { metadata as Bun13HtmlZhMetadata } from "@/content/posts/bun-1-3-html/zh-TW.mdx";
import Bun13HtmlEn, { metadata as Bun13HtmlEnMetadata } from "@/content/posts/bun-1-3-html/en.mdx";
import NpmClassicTokenZh, { metadata as NpmClassicTokenZhMetadata } from "@/content/posts/npm-classic-token/zh-TW.mdx";
import NpmClassicTokenEn, { metadata as NpmClassicTokenEnMetadata } from "@/content/posts/npm-classic-token/en.mdx";
import NuxtUiEditorZh, { metadata as NuxtUiEditorZhMetadata } from "@/content/posts/nuxt-ui-editor/zh-TW.mdx";
import NuxtUiEditorEn, { metadata as NuxtUiEditorEnMetadata } from "@/content/posts/nuxt-ui-editor/en.mdx";
import Jquery4Zh, { metadata as Jquery4ZhMetadata } from "@/content/posts/jquery-4/zh-TW.mdx";
import Jquery4En, { metadata as Jquery4EnMetadata } from "@/content/posts/jquery-4/en.mdx";
import MattPocockSkillsZh, { metadata as MattPocockSkillsZhMetadata } from "@/content/posts/matt-pocock-skills/zh-TW.mdx";
import MattPocockSkillsEn, { metadata as MattPocockSkillsEnMetadata } from "@/content/posts/matt-pocock-skills/en.mdx";
import CloudflareCrawlZh, { metadata as CloudflareCrawlZhMetadata } from "@/content/posts/cloudflare-crawl/zh-TW.mdx";
import CloudflareCrawlEn, { metadata as CloudflareCrawlEnMetadata } from "@/content/posts/cloudflare-crawl/en.mdx";
import Chrome147Zh, { metadata as Chrome147ZhMetadata } from "@/content/posts/chrome-147/zh-TW.mdx";
import Chrome147En, { metadata as Chrome147EnMetadata } from "@/content/posts/chrome-147/en.mdx";
import WebmcpZh, { metadata as WebmcpZhMetadata } from "@/content/posts/webmcp/zh-TW.mdx";
import WebmcpEn, { metadata as WebmcpEnMetadata } from "@/content/posts/webmcp/en.mdx";
import PostmanDatasetsZh, { metadata as PostmanDatasetsZhMetadata } from "@/content/posts/postman-datasets/zh-TW.mdx";
import PostmanDatasetsEn, { metadata as PostmanDatasetsEnMetadata } from "@/content/posts/postman-datasets/en.mdx";
import Typescript7Zh, { metadata as Typescript7ZhMetadata } from "@/content/posts/typescript-7/zh-TW.mdx";
import Typescript7En, { metadata as Typescript7EnMetadata } from "@/content/posts/typescript-7/en.mdx";
import ColdcardRngZh, { metadata as ColdcardRngZhMetadata } from "@/content/posts/coldcard-rng/zh-TW.mdx";
import ColdcardRngEn, { metadata as ColdcardRngEnMetadata } from "@/content/posts/coldcard-rng/en.mdx";
import ChaindropNpmZh, { metadata as ChaindropNpmZhMetadata } from "@/content/posts/chaindrop-npm/zh-TW.mdx";
import ChaindropNpmEn, { metadata as ChaindropNpmEnMetadata } from "@/content/posts/chaindrop-npm/en.mdx";
import { Locale } from "@/types/i18n";
import type { Post, PostMetadata } from "@/types/post";

function createPost(locale: Locale, Body: ComponentType, metadata: PostMetadata): Post {
  return { ...metadata, locale, Body };
}

export const topicPosts: Post[] = [
  createPost(Locale.ZH_TW, TailwindV4CssFirstZh, TailwindV4CssFirstZhMetadata),
  createPost(Locale.EN, TailwindV4CssFirstEn, TailwindV4CssFirstEnMetadata),
  createPost(Locale.ZH_TW, LetsencryptExpirationEmailsZh, LetsencryptExpirationEmailsZhMetadata),
  createPost(Locale.EN, LetsencryptExpirationEmailsEn, LetsencryptExpirationEmailsEnMetadata),
  createPost(Locale.ZH_TW, BybitSafeUiZh, BybitSafeUiZhMetadata),
  createPost(Locale.EN, BybitSafeUiEn, BybitSafeUiEnMetadata),
  createPost(Locale.ZH_TW, GithubSecretRiskAssessmentZh, GithubSecretRiskAssessmentZhMetadata),
  createPost(Locale.EN, GithubSecretRiskAssessmentEn, GithubSecretRiskAssessmentEnMetadata),
  createPost(Locale.ZH_TW, CustomSelectZh, CustomSelectZhMetadata),
  createPost(Locale.EN, CustomSelectEn, CustomSelectEnMetadata),
  createPost(Locale.ZH_TW, ChromeIo2025Zh, ChromeIo2025ZhMetadata),
  createPost(Locale.EN, ChromeIo2025En, ChromeIo2025EnMetadata),
  createPost(Locale.ZH_TW, FigmaSitesZh, FigmaSitesZhMetadata),
  createPost(Locale.EN, FigmaSitesEn, FigmaSitesEnMetadata),
  createPost(Locale.ZH_TW, Vite7BaselineZh, Vite7BaselineZhMetadata),
  createPost(Locale.EN, Vite7BaselineEn, Vite7BaselineEnMetadata),
  createPost(Locale.ZH_TW, Safari26WebPlatformZh, Safari26WebPlatformZhMetadata),
  createPost(Locale.EN, Safari26WebPlatformEn, Safari26WebPlatformEnMetadata),
  createPost(Locale.ZH_TW, TailwindPlusVanillaJsZh, TailwindPlusVanillaJsZhMetadata),
  createPost(Locale.EN, TailwindPlusVanillaJsEn, TailwindPlusVanillaJsEnMetadata),
  createPost(Locale.ZH_TW, CloudflareAiCrawlControlZh, CloudflareAiCrawlControlZhMetadata),
  createPost(Locale.EN, CloudflareAiCrawlControlEn, CloudflareAiCrawlControlEnMetadata),
  createPost(Locale.ZH_TW, NuxtUiV4Zh, NuxtUiV4ZhMetadata),
  createPost(Locale.EN, NuxtUiV4En, NuxtUiV4EnMetadata),
  createPost(Locale.ZH_TW, Bun13HtmlZh, Bun13HtmlZhMetadata),
  createPost(Locale.EN, Bun13HtmlEn, Bun13HtmlEnMetadata),
  createPost(Locale.ZH_TW, NpmClassicTokenZh, NpmClassicTokenZhMetadata),
  createPost(Locale.EN, NpmClassicTokenEn, NpmClassicTokenEnMetadata),
  createPost(Locale.ZH_TW, NuxtUiEditorZh, NuxtUiEditorZhMetadata),
  createPost(Locale.EN, NuxtUiEditorEn, NuxtUiEditorEnMetadata),
  createPost(Locale.ZH_TW, Jquery4Zh, Jquery4ZhMetadata),
  createPost(Locale.EN, Jquery4En, Jquery4EnMetadata),
  createPost(Locale.ZH_TW, MattPocockSkillsZh, MattPocockSkillsZhMetadata),
  createPost(Locale.EN, MattPocockSkillsEn, MattPocockSkillsEnMetadata),
  createPost(Locale.ZH_TW, CloudflareCrawlZh, CloudflareCrawlZhMetadata),
  createPost(Locale.EN, CloudflareCrawlEn, CloudflareCrawlEnMetadata),
  createPost(Locale.ZH_TW, Chrome147Zh, Chrome147ZhMetadata),
  createPost(Locale.EN, Chrome147En, Chrome147EnMetadata),
  createPost(Locale.ZH_TW, WebmcpZh, WebmcpZhMetadata),
  createPost(Locale.EN, WebmcpEn, WebmcpEnMetadata),
  createPost(Locale.ZH_TW, PostmanDatasetsZh, PostmanDatasetsZhMetadata),
  createPost(Locale.EN, PostmanDatasetsEn, PostmanDatasetsEnMetadata),
  createPost(Locale.ZH_TW, Typescript7Zh, Typescript7ZhMetadata),
  createPost(Locale.EN, Typescript7En, Typescript7EnMetadata),
  createPost(Locale.ZH_TW, ColdcardRngZh, ColdcardRngZhMetadata),
  createPost(Locale.EN, ColdcardRngEn, ColdcardRngEnMetadata),
  createPost(Locale.ZH_TW, ChaindropNpmZh, ChaindropNpmZhMetadata),
  createPost(Locale.EN, ChaindropNpmEn, ChaindropNpmEnMetadata),
];
